### ISSUE TITLE
contains_element function doesn't work as expected when the element is in the first position

### ISSUE THREAD

**Issue by meleu** [crcerror/RetroPie-RPM-BashROMManager#2]
If the console is `3do` (or any other value in the first element of the `console` array) then in [this line of code](https://github.com/crcerror/RetroPie-RPM-BashROMManager/blob/6576d3b381bdd9caa7e574725f40dc6914d01e57/BashROMManager.sh#L63):
```
contains_element "$i" "${console[@]}"
```
the function `contains_element` will return `0`. And according to your logic `0` means "System not found", wich is not true.

**Comment by meleu** [comment]
The approach I suggest:

```bash
function contains_element () {
    local e
    local match="$1"
    local idx=0
    shift
    for e; do
        if [[ "$e" == "$match" ]]; then
            echo "$idx"
            return 0
        fi
        idx=$((idx+1))
    done
    return 1
}
```

and then the caller of this function should do this:

```bash
console_idx="$(contains_element "$i" "${console[@]}")"
[[ -z "$console_idx" ]] && system_not_found_consequences...
```

If you agree with this approach you would need to check other places in the code where `contains_element` is used. ;)

**Comment by crcerror** [comment]
Thats indeed better

Annoter suggestion is to set idx timer before testcommand and return that value
but your suggestion is more general.... but I changed the return codes to...
Return 0 = ok
Return 1 = error, not found

**Comment by meleu** [comment]
> but I changed the return codes to...
Return 0 = ok
Return 1 = error, not found

:thinking: 

isn't it exactly what I suggested?

:sweat_smile:
